name = "graphml_writer"
description = "Write nodes and edges to GraphML format"
version = "0.0.0"
licenses = "BSD-3-Clause"
website = "https://github.com/TNO/Renaissance-Ada"
tags = ["graph", "graphml"]

authors = ["Pierre van de Laar"]
maintainers = ["Pierre van de Laar <pierre.van.de.laar@gmail.com>"]
maintainers-logins = ["pjljvandelaar"]
