name = "rejuvenation_lib_generator"
description = "Shiny new project"
version = "0.0.0"

executables = ["rejuvenation_lib_generator"]

[[depends-on]]
rejuvenation = "~0.0.0"

[[pins]]
rejuvenation = { path='../../libraries/Rejuvenation_Lib' }
