name: Ada (GNAT)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild
    
    - name: Set up libadalang
      run: >
        PREFIX=/tmp/ADALIB_DIR
        FILE=libadalang-linux-master-static.tar.gz
        
        mkdir -p $PREFIX &&
        aws s3 cp s3://adacore-gha-tray-eu-west-1/libadalang/$FILE . --sse=AES256 &&
        tar xzf $FILE -C $PREFIX &&
        rm -f -v $FILE

    - name: Set up GPR_PROJECT_PATH
      run: >
        echo $GPR_PROJECT_PATH &&
        export GPR_PROJECT_PATH=$PREFIX/share/gpr

    - name: Build
      run: gprbuild -k -s -P src/Renaissance_Ada.gpr
