name: Ada (GNAT)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Alire
      uses: alire-project/setup-alire@v1

    - name: Build
      run: cd src/libraries/Rejuvenation_Lib && alr build
