name: Ada (GNAT)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install 7zip
      run: sudo apt-get install p7zip-full
      
    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update && 
        sudo apt-get install gnat gprbuild
    
    - name: download libadalang
      run : wget https://github.com/TNO/Renaissance-Ada-Dependencies/releases/download/v22.1/libadalang-22.1-x86_64-linux-bin.tar.gz.zip

    - name: unzip libadalang
      shell: bash
      env: 
           UNZIP_PASSWORD: ${{ secrets.UNZIP_PASSWORD }}
      run: 7z x -p"$UNZIP_PASSWORD" libadalang-22.1-x86_64-linux-bin.tar.gz.zip
           
    - name: Set up libadalang
      run: > 
        mkdir -p /tmp/ADALIB_DIR &&
        tar xzf libadalang-22.1-x86_64-linux-bin.tar.gz -C /tmp &&
        rm -f -v libadalang-22.1-x86_64-linux-bin.tar.gz

    - name: check set up
      run : ls /tmp/libadalang-22.1-x86_64-linux-bin
      
    - name: Set up GPR_PROJECT_PATH
      run: >
        echo $GPR_PROJECT_PATH && 
        export GPR_PROJECT_PATH=/tmp/libadalang-22.1-x86_64-linux-bin/share/gpr

    - name: Build
      run: gprbuild -k -s -P src/Renaissance_Ada.gpr
